// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: Soil_Nutrient_try2

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_RootPanel;
lv_obj_t * ui_TopPanel;
lv_obj_t * ui_Title;
lv_obj_t * ui_AllValuePanel;
lv_obj_t * ui_TempPanel;
lv_obj_t * ui_KetTemp;
lv_obj_t * ui_TempValueLabel;
lv_obj_t * ui_UnitTemp;
lv_obj_t * ui_HumPanel;
lv_obj_t * ui_KetHum;
lv_obj_t * ui_HumValueLabel;
lv_obj_t * ui_UnitHum;
lv_obj_t * ui_PhPanel;
lv_obj_t * ui_KetPh;
lv_obj_t * ui_PhValueLabel;
lv_obj_t * ui_NPanel;
lv_obj_t * ui_KetN;
lv_obj_t * ui_NValueLabel;
lv_obj_t * ui_UnitN;
lv_obj_t * ui_PPanel;
lv_obj_t * ui_KetP;
lv_obj_t * ui_PValueLabel;
lv_obj_t * ui_UnitP;
lv_obj_t * ui_KPanel;
lv_obj_t * ui_KetK;
lv_obj_t * ui_KValueLabel;
lv_obj_t * ui_Label4;
lv_obj_t * ui_InfoPanel;
lv_obj_t * ui_Logo;
lv_obj_t * ui_InfoLabel;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
