// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: Soil_Nutrient_try2

#ifndef _SOIL_NUTRIENT_TRY2_UI_H
#define _SOIL_NUTRIENT_TRY2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_RootPanel;
extern lv_obj_t * ui_TopPanel;
extern lv_obj_t * ui_Title;
extern lv_obj_t * ui_AllValuePanel;
extern lv_obj_t * ui_TempPanel;
extern lv_obj_t * ui_KetTemp;
extern lv_obj_t * ui_TempValueLabel;
extern lv_obj_t * ui_UnitTemp;
extern lv_obj_t * ui_HumPanel;
extern lv_obj_t * ui_KetHum;
extern lv_obj_t * ui_HumValueLabel;
extern lv_obj_t * ui_UnitHum;
extern lv_obj_t * ui_PhPanel;
extern lv_obj_t * ui_KetPh;
extern lv_obj_t * ui_PhValueLabel;
extern lv_obj_t * ui_NPanel;
extern lv_obj_t * ui_KetN;
extern lv_obj_t * ui_NValueLabel;
extern lv_obj_t * ui_UnitN;
extern lv_obj_t * ui_PPanel;
extern lv_obj_t * ui_KetP;
extern lv_obj_t * ui_PValueLabel;
extern lv_obj_t * ui_UnitP;
extern lv_obj_t * ui_KPanel;
extern lv_obj_t * ui_KetK;
extern lv_obj_t * ui_KValueLabel;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_InfoPanel;
extern lv_obj_t * ui_Logo;
extern lv_obj_t * ui_InfoLabel;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1509005985);    // assets/Mask group (2).png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
